parameters:
#    it_blaster_config.example.class: ItBlaster\SingleConfigBundle\Example

services:
    it_blaster_single_config.admin.config:
        class: ItBlaster\SingleConfigBundle\Admin\ConfigAdmin
        arguments: [~, ItBlaster\SingleConfigBundle\Model\Config, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: propel, group: Администрирование, label: Администрирование}

    it_blaster_config.twig_extension:
        class: ItBlaster\SingleConfigBundle\Twig\ItBlasterSingleConfigExtension
        tags:
            - { name: twig.extension }